site_title = "Arxiv Robotics"
limit_days = 30
cache_url = "https://UltramarineW.github.io/Robotics-Arxiv-Daily/cache.json"

[[sources]]
limit = 300
category = "cs.RO"
title = "Robotics"

[[sources]]
limit = 300
category = "cs.CV"
title = "Computer Vision and Pattern Recognition"

[[sources]]
limit = 300
category = "cs.AI"
title = "Artificial Intelligence"

[[sources]]
limit = 300
category = "cs.LG"
title = "Machine Learning"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
 
